### ISSUE TITLE
Handle alignments for columns in index mode

### ISSUE THREAD

**Issue by trou** [lumail/lumail#161]
It would be nice to be able to specify fields to be aligned in `index_format` to improve readability.

Specifying absolute numbers seems bad because it won't play nice with different terminal sizes. Maybe relative sizes ? 

I'll see if I can implement this feature.

**Comment by skx** [comment]
I'm sorry for the lack of update on this issue, but work on lumail has been pretty much abandoned.  

The good news is that there is a new project, [lumail2](https://github.com/lumail/lumail2/) which is very similar to this one:

* It is still console-based.
* It still operates solely on Maildir hierarchies.
* It is still written in C++, with all the scripting support provided by Lua.

Why change?  Lots of reasons, but primarily because I wanted everything to be an object: Messages, Maildirs, etc.  The rewrite is more functional than the older-codebase, smaller, simpler, and much more flexible.

If you're still interested in Lumail please do take a look:

* https://github.com/lumail/lumail2/
