### ISSUE TITLE
Can't modify body after display

### ISSUE THREAD

**Issue by trou** [lumail/lumail#173]
I recently encountered a problem I don't know how to handle in lumail : the text/plain part of the message was so bad I wanted to switch the view to the "lynx -dump" of the HTML version of the message. Except  that `on_get_body` seems the only way to alter the display.
Is there a way to call a function to alter the body afterwards ?

**Comment by skx** [comment]
I'm sorry for the lack of update on this issue, but work on lumail has been pretty much abandoned.  

The good news is that there is a new project, [lumail2](https://github.com/lumail/lumail2/) which is very similar to this one:

* It is still console-based.
* It still operates solely on Maildir hierarchies.
* It is still written in C++, with all the scripting support provided by Lua.

Why change?  Lots of reasons, but primarily because I wanted everything to be an object: Messages, Maildirs, etc.  The rewrite is more functional than the older-codebase, smaller, simpler, and much more flexible.

If you're still interested in Lumail please do take a look:

* https://github.com/lumail/lumail2/
