### ISSUE TITLE
Wrong recipients when replying to a message with lumail user in Cc

### ISSUE THREAD

**Issue by paulepanter** [lumail/lumail#174]
Replying to a message using the `r` key with the following sender and receivers, where the lumail user is in CC (Carbon Copy)

    To: A A <a@example.net>
    Cc: B B <b@example.net>,  My Self <myself@example.net>
    From: Joe Sender <sender@example.net>

the result is that myself is going into the CC field of the reply and the original recipient is left out.

    To: Joe Sender <sender@example.net>
    Cc: B B <b@example.net>,  My Self <myself@example.net>

So I guess the `Cc` field of the reply needs to be adapted and the addresses in the original `To` field be added and myself be removed.

**Comment by skx** [comment]
I'm sorry for the lack of update on this issue, but work on lumail has been pretty much abandoned.  

The good news is that there is a new project, [lumail2](https://github.com/lumail/lumail2/) which is very similar to this one:

* It is still console-based.
* It still operates solely on Maildir hierarchies.
* It is still written in C++, with all the scripting support provided by Lua.

Why change?  Lots of reasons, but primarily because I wanted everything to be an object: Messages, Maildirs, etc.  The rewrite is more functional than the older-codebase, smaller, simpler, and much more flexible.

If you're still interested in Lumail please do take a look:

* https://github.com/lumail/lumail2/
