### ISSUE TITLE
Compressed folder support?

### ISSUE THREAD

**Issue by jugglerchris** [lumail/lumail#193]
Hi,

Would you consider including support for some kind of compressed (local) mailbox?  (eg if someone had the energy to implement it, would you ever merge it in?)

I'm looking into mutt alternatives (I like mutt, but prefer scriptability to sea-of-options).  mutt supports using a gzipped mbox (by providing hooks on open/close/append).  I make use of this - I archive older mail into an mbox.gz to save space, while still being accessible.

This would be particularly handy with lumail's multiple-mailbox support to seamlessly merge the archive and "current" mailboxes.

Thanks,

Chris

**Comment by skx** [comment]
I'm sorry for the lack of update on this issue, but work on lumail has been pretty much abandoned.  

The good news is that there is a new project, [lumail2](https://github.com/lumail/lumail2/) which is very similar to this one:

* It is still console-based.
* It still operates solely on Maildir hierarchies.
* It is still written in C++, with all the scripting support provided by Lua.

Why change?  Lots of reasons, but primarily because I wanted everything to be an object: Messages, Maildirs, etc.  The rewrite is more functional than the older-codebase, smaller, simpler, and much more flexible.

If you're still interested in Lumail please do take a look:

* https://github.com/lumail/lumail2/
