### ISSUE TITLE
More general maildir_format()

### ISSUE THREAD

**Issue by jugglerchris** [lumail/lumail#205]
Hi,

I'd find it useful to have better control of maildir display than I can get with maildir_format().  eg I have some hierarchical maildirs a bit like:

/home/chris/mail/lists/somelist
/home/chris/mail/lists/foo
/home/chris/mail/lists/bar
/home/chris/mail/misc/foo

and some similar ones in a separate area, using the "Maildir/.folder.subfolder" format (needed by the IMAP server):

/home/chris/popboxes/user%example.com/Maildir/.lists.baz
/home/chris/popboxes/user%example.com/Maildir/.lists.qux

I've got the choice of $PATH (too long - may not fit on the screen) or $NAME (not enough context).  I really want them to show more uniformly, but distinguishing between locations somehow:

lists/somelist
lists/foo
lists/bar
misc/foo
lists/baz [IMAP]
lists/qux [IMAP]

A good (for me) solution would be to allow passing a Lua function to maildir_format(); this would need similar access to CMaildir objects as in issue #204.

**Comment by skx** [comment]
I'm sorry for the lack of update on this issue, but work on lumail has been pretty much abandoned.  

The good news is that there is a new project, [lumail2](https://github.com/lumail/lumail2/) which is very similar to this one:

* It is still console-based.
* It still operates solely on Maildir hierarchies.
* It is still written in C++, with all the scripting support provided by Lua.

Why change?  Lots of reasons, but primarily because I wanted everything to be an object: Messages, Maildirs, etc.  The rewrite is more functional than the older-codebase, smaller, simpler, and much more flexible.

If you're still interested in Lumail please do take a look:

* https://github.com/lumail/lumail2/
