### ISSUE TITLE
maildirs_matching() or something similar should maybe ignore maildir_limit

### ISSUE THREAD

**Issue by jugglerchris** [lumail/lumail#208]
Hi,

It would be useful to have a primitive to get the full list of maildirs rather than the one filtered by maildir_limit (and any future Lua filter).

My use case is picking a folder to save a message to; I'm quite likely to want to save to a folder that's not visible in the current maildir mode.

Rather than having to temporarily reassign maildir_limit (and the Lua filter function), it would feel cleaner to pass extra parameters to maildirs_matching() (or to a new more general primitive) to override them.

**Comment by skx** [comment]
I'm sorry for the lack of update on this issue, but work on lumail has been pretty much abandoned.  

The good news is that there is a new project, [lumail2](https://github.com/lumail/lumail2/) which is very similar to this one:

* It is still console-based.
* It still operates solely on Maildir hierarchies.
* It is still written in C++, with all the scripting support provided by Lua.

Why change?  Lots of reasons, but primarily because I wanted everything to be an object: Messages, Maildirs, etc.  The rewrite is more functional than the older-codebase, smaller, simpler, and much more flexible.

If you're still interested in Lumail please do take a look:

* https://github.com/lumail/lumail2/
