### ISSUE TITLE
Saving a message to a folder programatically

### ISSUE THREAD

**Issue by jugglerchris** [lumail/lumail#216]
I'm trying to write a function in my config.lua to move all read messages in a folder to another folder.
On a branch I've exposed `CMaildir::getMessages` to Lua, so that I can iterate through them more conveniently than using `jump_index_to`, especially if I'm going to be deleting some of them and causing renumberings.
But the only way (as far as I can see) of saving a message to a folder is for it to be the current message and calling `save`.
So I'd quite like to move the middle part of `save_message` into a `CMessage` method (or maybe two - one to copy to a new folder and another to delete).  `CMessage::save_to(string dest, bool delete_orig)`, say.
However I'm then not too sure about the `global->update_messages()` call; I don't really want to do it for each of the 100 messages I'm saving in one go, as that sounds pretty slow.  My best idea so far is to invalidate global->m_messages if the moved message's maildir is one of the current ones, and rebuild the list on demand in `CGlobal::get_messages()`.
(End of pre-sleep brain dump.)

**Comment by skx** [comment]
I'm sorry for the lack of update on this issue, but work on lumail has been pretty much abandoned.  

The good news is that there is a new project, [lumail2](https://github.com/lumail/lumail2/) which is very similar to this one:

* It is still console-based.
* It still operates solely on Maildir hierarchies.
* It is still written in C++, with all the scripting support provided by Lua.

Why change?  Lots of reasons, but primarily because I wanted everything to be an object: Messages, Maildirs, etc.  The rewrite is more functional than the older-codebase, smaller, simpler, and much more flexible.

If you're still interested in Lumail please do take a look:

* https://github.com/lumail/lumail2/
