### ISSUE TITLE
Forwarding a message should also forward the attachments

### ISSUE THREAD

**Issue by paulepanter** [lumail/lumail#220]
Current in lumail v0.25 forwarding a message with attachments, only the actual mail text is forwarded and not the attachments.

I know of the following solutions.

1. Evolution somehow attaches the whole message (with the attachments). Unfortunately some MUAs (especially Web interfaces (<http://www.freenet.de> and <http://www.gmx.de/>) do not know how to deal with this. But this is configurable.

2. Mozilla Thunderbird attaches all the attachments to the forwarded messages. The advantage is that more MUAs are able to handle such a message. The downside is, that it is not clear, what attachments belong to the forwarded message.

**Comment by skx** [comment]
I'm sorry for the lack of update on this issue, but work on lumail has been pretty much abandoned.  

The good news is that there is a new project, [lumail2](https://github.com/lumail/lumail2/) which is very similar to this one:

* It is still console-based.
* It still operates solely on Maildir hierarchies.
* It is still written in C++, with all the scripting support provided by Lua.

Why change?  Lots of reasons, but primarily because I wanted everything to be an object: Messages, Maildirs, etc.  The rewrite is more functional than the older-codebase, smaller, simpler, and much more flexible.

If you're still interested in Lumail please do take a look:

* https://github.com/lumail/lumail2/
