### ISSUE TITLE
GLib-GObject-WARNING **: invalid cast from `GMimeMultipartEncrypted' to `GMimePart'

### ISSUE THREAD

**Issue by paulepanter** [lumail/lumail#225]
Opening an encrypted message without encrypting it, the following messages are printed across the window.

    (process:4037): GLib-GObject-WARNING **: invalid cast from `GMimeMultipartEncrypted' to `GMimePart'
    (process:4037): gmime-CRITICAL **: g_mime_part_get_content_object: assertion `GMIME_IS_PART (mime_part)' failed
    (process:4037): gmime-CRITICAL **: g_mime_data_wrapper_write_to_stream: assertion `GMIME_IS_DATA_WRAPPER (wrapper)' failed

**Comment by skx** [comment]
I'm sorry for the lack of update on this issue, but work on lumail has been pretty much abandoned.  

The good news is that there is a new project, [lumail2](https://github.com/lumail/lumail2/) which is very similar to this one:

* It is still console-based.
* It still operates solely on Maildir hierarchies.
* It is still written in C++, with all the scripting support provided by Lua.

Why change?  Lots of reasons, but primarily because I wanted everything to be an object: Messages, Maildirs, etc.  The rewrite is more functional than the older-codebase, smaller, simpler, and much more flexible.

If you're still interested in Lumail please do take a look:

* https://github.com/lumail/lumail2/
