### ISSUE TITLE
current_message() returning a CMessage object?

### ISSUE THREAD

**Issue by jugglerchris** [lumail/lumail#234]
Analogously to the `current_maildir` change from #214, would you consider a pull request changing `current_message` return a `CMessage` object instead of the path, or else adding a new function which did this?

I tried using `index_offset` with `current_maildir():getMessages()`, but I wasn't getting matching indices (I haven't looked into whether that's expected or a bug; I've come back to looking at my lumail setup after being busy with other stuff)

**Comment by skx** [comment]
I'm sorry for the lack of update on this issue, but work on lumail has been pretty much abandoned.  

The good news is that there is a new project, [lumail2](https://github.com/lumail/lumail2/) which is very similar to this one:

* It is still console-based.
* It still operates solely on Maildir hierarchies.
* It is still written in C++, with all the scripting support provided by Lua.

Why change?  Lots of reasons, but primarily because I wanted everything to be an object: Messages, Maildirs, etc.  The rewrite is more functional than the older-codebase, smaller, simpler, and much more flexible.

If you're still interested in Lumail please do take a look:

* https://github.com/lumail/lumail2/
