### ISSUE TITLE
Some notes on OSX installation

### ISSUE THREAD

**Issue by larryhynes** [lumail/lumail#238]
I'm not sure how much of a priority OSX support is for you but I thought I would jot down the following while it is still fresh in my mind.

The `curses` that ships with OSX does not support wide characters. A version that *does* support wide chars can be installed with Homebrew (package manager, sort of), but it is not symlinked into place in order not to upset the incumbent system curses.

This means that `$(shell pkg-config --cflags ncursesw)` and `$(shell pkg-config --libs ncursesw)` in the Makefile both fail, despite the necessary libs and headers being available.

(I've made note of this with the Homebrew people [here](https://github.com/Homebrew/homebrew-dupes/issues/455))

If OSX support is something you're interested in I'm sure there's more than one easy way to ensure a happy ending... a note in the README would probably smooth a lot of it over. I can draft something for your approval if you like.

**Comment by mistydemeo** [comment]
> The curses that ships with OSX does not support wide characters.

For reference, OS X's ncurses is (confusingly) installed only under the `ncurses` name, but it is built with wide character support!

**Comment by larryhynes** [comment]
@mistydemeo I did not know that - thank you! Why, then, when something calls for wide char support - like [sup](https://github.com/sup-heliotrope/sup/wiki/Mac-OSX), for instance - is there a clamour for a non-system curses for osx? Is it just that a *newer* version is required?

**Comment by skx** [comment]
I'm sorry for the lack of update on this issue, but work on lumail has been pretty much abandoned.  

The good news is that there is a new project, [lumail2](https://github.com/lumail/lumail2/) which is very similar to this one:

* It is still console-based.
* It still operates solely on Maildir hierarchies.
* It is still written in C++, with all the scripting support provided by Lua.

Why change?  Lots of reasons, but primarily because I wanted everything to be an object: Messages, Maildirs, etc.  The rewrite is more functional than the older-codebase, smaller, simpler, and much more flexible.

If you're still interested in Lumail please do take a look:

* https://github.com/lumail/lumail2/
