### ISSUE TITLE
Unending alert when opening a moved message

### ISSUE THREAD

**Issue by jugglerchris** [lumail/lumail#239]
I just tried to open a new message at exactly the time when a separate mail client (my phone via IMAP) happened to cause the message to (I think) be moved from the new/ to cur/ part of the Maildir.  lumail put up an alert due to failing to open the message, which I couldn't easily cancel - typing RET just seemed to reset the timeout and I eventually killed it with C-c.  Sorry I didn't get more debugging information; I can only guess it tried to open it again as it was still in the message view.

I think better behaviour would be to give up, refresh the index, and go back to the index mode (unless it can follow the message to cur/ and open it there).

**Comment by skx** [comment]
I'm sorry for the lack of update on this issue, but work on lumail has been pretty much abandoned.  

The good news is that there is a new project, [lumail2](https://github.com/lumail/lumail2/) which is very similar to this one:

* It is still console-based.
* It still operates solely on Maildir hierarchies.
* It is still written in C++, with all the scripting support provided by Lua.

Why change?  Lots of reasons, but primarily because I wanted everything to be an object: Messages, Maildirs, etc.  The rewrite is more functional than the older-codebase, smaller, simpler, and much more flexible.

If you're still interested in Lumail please do take a look:

* https://github.com/lumail/lumail2/
