### ISSUE TITLE
page_down() scrolls too far

### ISSUE THREAD

**Issue by jugglerchris** [lumail/lumail#240]
Hi,

The `page_down()` and `page_up()` functions in the default lumail.lua scrolls too far in messages, as it doesn't take into account the non-scrolling space used for headers and attachments.

Something like:

```lua
function message_header_height()
    -- Scrollable area doesn't include headers, attachment list, or
    -- the blank line between.
    return #headers + (show_attachments and count_body_parts() or 0) + 1
end
...
function page_down()
...
   elseif (string.find(m, 'message') ) then
      scroll_message_down( screen_height() - 2 - message_header_height())
```
seems to improve things.

**Comment by skx** [comment]
Happy to accept a pull-request for updated function(s) for the defaults.

Sorry for the slow reply.

**Comment by skx** [comment]
I'm sorry for the lack of update on this issue, but work on lumail has been pretty much abandoned.  

The good news is that there is a new project, [lumail2](https://github.com/lumail/lumail2/) which is very similar to this one:

* It is still console-based.
* It still operates solely on Maildir hierarchies.
* It is still written in C++, with all the scripting support provided by Lua.

Why change?  Lots of reasons, but primarily because I wanted everything to be an object: Messages, Maildirs, etc.  The rewrite is more functional than the older-codebase, smaller, simpler, and much more flexible.

If you're still interested in Lumail please do take a look:

* https://github.com/lumail/lumail2/
