### ISSUE TITLE
Invalid stack indixes (cause crashes when running with LuaJIT)

### ISSUE THREAD

**Issue by jugglerchris** [lumail/lumail#242]
Hi,
I tried building Lumail with LuaJIT, and it crashes pretty quickly, because quite a few of the primitives pass invalid negative indices to eg lua_tostring().

An example (the first one caught by LUA_APICHECK) is global_mode:

```lua
int global_mode(lua_State * L)                       
{                                                    
    /**                                              
     * This is valid only if we're setting the limit.
     */                                              
    const char *new_mode = lua_tostring(L, -1);
```
When called with no arguments, -1 is not a valid or acceptable index; changing it to 1 is ok (it's acceptable have a positive index above the stack top here).  There are lots of other instances of the same thing.

I'm guessing that LuaJIT compatibility isn't high on the priority list, but I'm raising this for future reference at least.

Chris

**Comment by skx** [comment]
If these are invalid indexes then I guess they need to be fixed regardless of JIT-usage.

I guess it's not a big job to patch them up, to use `lua_gettop in the right places, but it'll be a lot of churn.  Any help identifying the troublesome spots would be most welcome.

I've always tended to prefer the negative, but a gradual migration to the postive wouldn't hurt.  Though I still keep thinking I should pick up lumail2 instead ;)

**Comment by jugglerchris** [comment]
I think just using 1,2 etc is the right thing to do - you want the first, second arguments rather than the last or last-but-one. Using positive indices beyond the last arg is usually allowed.
I've got a bunch of changes in my local fork; at some point I plan to feed back when things are a bit tidier and finished.

**Comment by skx** [comment]
I'd be happy to update if there were correctness fixes.

(Actually switching to positive integers, even in the case of no bugs, is probably worthwhile.  I'm sure the churn would be high to mass-update, but I will accept pull-requests which make even minor progress in that direction.)

**Comment by skx** [comment]
I'm sorry for the lack of update on this issue, but work on lumail has been pretty much abandoned.  

The good news is that there is a new project, [lumail2](https://github.com/lumail/lumail2/) which is very similar to this one:

* It is still console-based.
* It still operates solely on Maildir hierarchies.
* It is still written in C++, with all the scripting support provided by Lua.

Why change?  Lots of reasons, but primarily because I wanted everything to be an object: Messages, Maildirs, etc.  The rewrite is more functional than the older-codebase, smaller, simpler, and much more flexible.

If you're still interested in Lumail please do take a look:

* https://github.com/lumail/lumail2/
