### ISSUE TITLE
Opening a maildir requires gpg interaction

### ISSUE THREAD

**Issue by fischerling** [lumail/lumail#298]
When I open my INBOX with encrypted mails in it, I have to unlock my gpg key even if I don't want to open those encrypted mails.

This happens because during construction of CMessages the lua function `message_replace` is called.

It would be a great improvement if we only call `message_replace` in `message_view`.

**Comment by fischerling** [comment]
I am sorry. The mimeparts are parsed in `msg::format` to find a gpg signature and not at CMessage construction time.
The backtrace look something like this.

    index_view
      -> format_message
        -> mimeparts2table
          -> msg::parts
            -> message_replace

**Comment by skx** [comment]
I'll need to test this and see.  I suspect the issue is:

* We parse the headers to format the message.
    * We need to parse the message to get the headers.
    * When the body is encrypted we ask for it - because we're parsing the message.

It is possible we could parse the headers without reading/processing the body, but that would be a net-loss if we did it everywhere.  e.g. Displaying a message (in message-mode) clearly needs access to both parts, but we should avoid reading the message from-disk/from-IMAP twice.

**Comment by fischerling** [comment]
This is partly solved with #342.
gpg interaction is now only needed when opening a maildir for the first time.
